# Generated by Django 4.1.7 on 2023-04-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyecBazarApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='run_usuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comuna_FK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyecBazarApp.comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_FK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyecBazarApp.rol'),
        ),
    ]
