# Generated by Django 4.1.7 on 2023-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyecBazarApp', '0002_remove_usuario_run_usuario_alter_usuario_comuna_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='razon_social_cliente',
            field=models.CharField(default=1, max_length=45),
        ),
        migrations.AddField(
            model_name='detalleboletas',
            name='total',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detallefacturas',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
