# Generated by Django 4.1.7 on 2023-04-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyecBazarApp', '0003_cliente_razon_social_cliente_detalleboletas_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=1, max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social_cliente',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='detalleboletas',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallefacturas',
            name='total',
            field=models.IntegerField(),
        ),
    ]
