# Generated by Django 4.1.7 on 2023-04-16 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyecBazarApp', '0004_cliente_direccion_alter_cliente_razon_social_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='usuario_FK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturas',
            name='usuario_FK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comuna_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyecBazarApp.comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyecBazarApp.rol'),
        ),
    ]
