# Generated by Django 4.1.7 on 2023-04-16 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyecBazarApp', '0005_boletas_usuario_fk_facturas_usuario_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletas',
            name='usuario_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='usuario_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
