# Generated by Django 4.1.7 on 2023-04-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyecBazarApp', '0006_alter_boletas_usuario_fk_alter_facturas_usuario_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletas',
            name='usuario_FK',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='usuario_FK',
        ),
    ]
