# Generated by Django 4.1.7 on 2023-04-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyecBazarApp', '0007_remove_boletas_usuario_fk_remove_facturas_usuario_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usuario_FK',
        ),
    ]
