# Generated by Django 4.1.7 on 2023-04-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyecBazarApp', '0010_alter_boletas_usuario_fk_alter_facturas_usuario_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletas',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
