# Generated by Django 4.1.7 on 2023-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyecBazarApp', '0011_alter_boletas_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=1, upload_to='productos'),
        ),
    ]
