# Generated by Django 4.1.7 on 2023-04-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyecBazarApp', '0012_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='condicion_venta_FK',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.DeleteModel(
            name='CondicionVenta',
        ),
    ]
