# Generated by Django 4.1.7 on 2023-04-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyecBazarApp', '0013_remove_facturas_condicion_venta_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
